// Generated by CoffeeScript 1.8.0
var Butter;

module.exports = Butter = (function() {
  function Butter(startCount, endCount, totalChurn, activity, days) {
    this.startCount = startCount;
    this.endCount = endCount;
    this.totalChurn = totalChurn;
    this.activity = activity;
    this.days = days;
  }

  Butter.prototype.churn = function() {
    var churnPerDay, customerDays, netAdd;
    netAdd = this.endCount - this.startCount;
    customerDays = (this.startCount * this.days) + (this.activity * this.netAdd * this.days);
    churnPerDay = this.totalChurn / customerDays;
    return this.days * churnPerDay;
  };

  return Butter;

})();
